2024-11-05 15:17:52.762 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
2024-11-05 15:17:52.763 | INFO     | sc2.controller:create_game:37 - Creating new game
2024-11-05 15:17:52.764 | INFO     | sc2.controller:create_game:38 - Map:     Oceanborn513AIE
2024-11-05 15:17:52.765 | INFO     | sc2.controller:create_game:39 - Players: Bot LadderBot(Terran), Computer VeryHard(Zerg, RandomBuild)
2024-11-05 15:17:52.768 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
2024-11-05 15:18:09.938 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
2024-11-05 15:18:09.939 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot LadderBot(Terran)
2024-11-05 15:18:10.979 | 00:00    0ms    0M    0G  12/ 15U [Version] 5.0.13.92440
2024-11-05 15:18:10.980 | 00:00    0ms    0M    0G  12/ 15U [Version] 5.0.6 Balance mod recognized.
2024-11-05 15:18:11.165 | 00:00    0ms    0M    0G  12/ 15U [ZoneManager] Map set to: MapName.Unknown from name: Oceanborn AIE and hash: 3562128.
2024-11-05 15:18:13.225 | 00:00    0ms    0M    0G  12/ 15U [Build] Att at 197
2024-11-05 15:18:13.227 | ERROR    | sc2.main:initialize_first_step:140 - Caught unknown exception in AI on_start: UpgradeId.YAMATOCANNON
Traceback (most recent call last):

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\run.py", line 18, in <module>
    main()
    └ <function main at 0x000002E28FD7EB60>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\run.py", line 13, in main
    result, opponentid = run_ladder_game(protoss_bot)
                         │               └ <sc2.player.Bot object at 0x000002E28D886A90>
                         └ <function run_ladder_game at 0x000002E2F444B740>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\ladder.py", line 39, in run_ladder_game
    return stand_alone_game(bot), None
           │                └ <sc2.player.Bot object at 0x000002E28D886A90>
           └ <function stand_alone_game at 0x000002E28D5B0A40>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\ladder.py", line 166, in stand_alone_game
    return sc2.main.run_game(sc2.maps.get(map_name), [bot, Computer(Race.Zerg, Difficulty.VeryHard)], realtime=False,)
           │   │    │        │   │    │   │           │    │        │    │     │          └ <Difficulty.VeryHard: 7>
           │   │    │        │   │    │   │           │    │        │    │     └ <enum 'Difficulty'>
           │   │    │        │   │    │   │           │    │        │    └ <Race.Zerg: 2>
           │   │    │        │   │    │   │           │    │        └ <enum 'Race'>
           │   │    │        │   │    │   │           │    └ <class 'sc2.player.Computer'>
           │   │    │        │   │    │   │           └ <sc2.player.Bot object at 0x000002E28D886A90>
           │   │    │        │   │    │   └ 'Oceanborn513AIE'
           │   │    │        │   │    └ <function get at 0x000002E28D61E160>
           │   │    │        │   └ <module 'sc2.maps' from 'c:\\Users\\Lena\\AppData\\Local\\Bots\\DemonT\\sc2\\maps.py'>
           │   │    │        └ <module 'sc2' from 'c:\\Users\\Lena\\AppData\\Local\\Bots\\DemonT\\sc2\\__init__.py'>
           │   │    └ <function run_game at 0x000002E28D772700>
           │   └ <module 'sc2.main' from 'c:\\Users\\Lena\\AppData\\Local\\Bots\\DemonT\\sc2\\main.py'>
           └ <module 'sc2' from 'c:\\Users\\Lena\\AppData\\Local\\Bots\\DemonT\\sc2\\__init__.py'>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\sc2\main.py", line 496, in run_game
    result: Result = asyncio.run(_host_game(map_settings, players, **kwargs))
                     │       │   │          │             │          └ {'realtime': False}
                     │       │   │          │             └ [<sc2.player.Bot object at 0x000002E28D886A90>, <sc2.player.Computer object at 0x000002E28E85B1D0>]
                     │       │   │          └ Map(D:\StarCraft II\maps\Oceanborn513AIE.SC2Map)
                     │       │   └ <function _host_game at 0x000002E28D7722A0>
                     │       └ <function run at 0x000002E2F6386020>
                     └ <module 'asyncio' from 'C:\\Users\\Lena\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>

  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object _host_game at 0x000002E2F6F91900>
           │      └ <function Runner.run at 0x000002E2F67F6020>
           └ <asyncio.runners.Runner object at 0x000002E28DD165D0>
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<_host_game() running at c:\Users\Lena\AppData\Local\Bots\DemonT\sc2\main.py:369> cb=[_run_u...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000002E2F67EFB00>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000002E28DD165D0>
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002E2F68BFC40>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002E2F67F58A0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002E2F634AE80>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\sc2\main.py", line 369, in _host_game
    result = await _play_game(players[0], client, realtime, portconfig, game_time_limit, rgb_render_config)
                   │          │           │       │         │           │                └ None
                   │          │           │       │         │           └ None
                   │          │           │       │         └ None
                   │          │           │       └ False
                   │          │           └ <sc2.client.Client object at 0x000002E28FDAA710>
                   │          └ [<sc2.player.Bot object at 0x000002E28D886A90>, <sc2.player.Computer object at 0x000002E28E85B1D0>]
                   └ <function _play_game at 0x000002E28D7720C0>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\sc2\main.py", line 226, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, game_time_limit)
                   │             │       │          │      │   │         └ None
                   │             │       │          │      │   └ False
                   │             │       │          │      └ <dummy.dummy.LadderBot object at 0x000002E28E9DAB10>
                   │             │       │          └ <sc2.player.Bot object at 0x000002E28D886A90>
                   │             │       └ 1
                   │             └ <sc2.client.Client object at 0x000002E28FDAA710>
                   └ <function _play_game_ai at 0x000002E28D771F80>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\sc2\main.py", line 145, in _play_game_ai
    result = await initialize_first_step()
                   └ <function _play_game_ai.<locals>.initialize_first_step at 0x000002E28FD7F740>

> File "c:\Users\Lena\AppData\Local\Bots\DemonT\sc2\main.py", line 136, in initialize_first_step
    await ai.on_start()
          │  └ <function KnowledgeBot.on_start at 0x000002E28FB76A20>
          └ <dummy.dummy.LadderBot object at 0x000002E28E9DAB10>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\sharpy\knowledges\knowledge_bot.py", line 71, in on_start
    await self.knowledge.start()
          │    │         └ <function Knowledge.start at 0x000002E28D7FC040>
          │    └ <sharpy.knowledges.knowledge.Knowledge object at 0x000002E28FAEAE90>
          └ <dummy.dummy.LadderBot object at 0x000002E28E9DAB10>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\sharpy\knowledges\knowledge.py", line 151, in start
    await manager.post_start()
          │       └ <function ActManager.post_start at 0x000002E28D5FE480>
          └ <sharpy.managers.core.act_manager.ActManager object at 0x000002E28E0DFE10>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\sharpy\managers\core\act_manager.py", line 25, in post_start
    self._act = await self._act_or_func()
    │                 │    └ <bound method BattleCruisers.create_plan of <dummy.dummy.LadderBot object at 0x000002E28E9DAB10>>
    │                 └ <sharpy.managers.core.act_manager.ActManager object at 0x000002E28E0DFE10>
    └ <sharpy.managers.core.act_manager.ActManager object at 0x000002E28E0DFE10>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\dummy\dummy.py", line 153, in create_plan
    Tech(UpgradeId.YAMATOCANNON),
    │    │         └ UpgradeId.YAMATOCANNON
    │    └ <enum 'UpgradeId'>
    └ <class 'sharpy.plans.acts.tech.Tech'>

  File "c:\Users\Lena\AppData\Local\Bots\DemonT\sharpy\plans\acts\tech.py", line 39, in __init__
    from_building = UPGRADE_RESEARCHED_FROM[self.upgrade_type]
                    │                       │    └ UpgradeId.YAMATOCANNON
                    │                       └ <sharpy.plans.acts.tech.Tech object at 0x000002E28FE13350>
                    └ {UpgradeId.ADEPTPIERCINGATTACK: UnitTypeId.TWILIGHTCOUNCIL, UpgradeId.ANABOLICSYNTHESIS: UnitTypeId.ULTRALISKCAVERN, UpgradeI...

KeyError: UpgradeId.YAMATOCANNON
2024-11-05 15:18:13.307 | ERROR    | sc2.main:initialize_first_step:141 - Resigning due to previous error
2024-11-05 15:18:13.308 | Result: Defeat
2024-11-05 15:18:13.309 | Duration: 00:00
2024-11-05 15:18:13.310 | Step time avg: 0
2024-11-05 15:18:13.310 | Step time max: 0
2024-11-05 15:18:13.311 | [LostUnitsContents] My lost units minerals and gas: (0, 0)
2024-11-05 15:18:13.311 | [LostUnitsContents] My lost units minerals by score: 0.0
2024-11-05 15:18:13.312 | [LostUnitsContents] Enemy lost units minerals and gas: (0, 0)
2024-11-05 15:18:13.312 | [LostUnitsContents] Enemy lost units minerals by score: 0.0
2024-11-05 15:18:13.313 | [GameAnalyzerEnd] Own units:
2024-11-05 15:18:13.313 | [GameAnalyzerEnd] Enemy units:
2024-11-05 15:18:13.314 | [GameAnalyzerEnd] Minerals max 0 Average 0
2024-11-05 15:18:13.323 | [GameAnalyzerEnd] Vespene max 0 Average 0
2024-11-05 15:18:13.324 | INFO     | sc2.main:_play_game:228 - Result for player 1 - Bot LadderBot(Terran): Defeat
2024-11-05 15:18:14.955 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was Status.in_game)
2024-11-05 15:18:14.977 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.quit (was Status.launched)
2024-11-05 15:18:14.978 | INFO     | sc2.sc2process:_close_connection:231 - Closing connection at 59786...
2024-11-05 15:18:14.980 | INFO     | sc2.sc2process:kill_all:33 - kill_switch: Process cleanup for 1 processes
